### ISSUE TITLE
img.shields.io is down

### ISSUE THREAD

**Issue by slang800** [badges/buckler#30]
![1443578576](https://cloud.githubusercontent.com/assets/1049204/10182759/e2890118-66f5-11e5-8c7a-0284c5f703b1.png)

**Comment by nathany** [comment]
Hi. img.shields.io is running https://github.com/badges/shields. I don't think Buckler is being used at all.

But it looks like it's working again now, so I'm closing this issue.

**Comment by slang800** [comment]
oh, sorry about the misplaced issue!
