### ISSUE TITLE
Shippable build not working for branches except master

### ISSUE THREAD

**Issue by mbrodala** [badges/buckler#31]
I've noticed that images for Shippable builds are not working for branches except master.

Thus the following three images always yield the same result (from master):

```
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/master.svg
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/staging.svg
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/production.svg
```

As soon as we trigger a build on master, all three badges change to `build | pending` and return to `build | passing` after it completes. A build on `staging` and `production` do not yield any change.

**Comment by nathany** [comment]
Fyi, Buckler isn't being used for img.shields.io. Your issue may not be noticed unless you report it at: https://github.com/badges/shields

**Comment by mbrodala** [comment]
@nathany Thanks no idea how I did end up here. I'll do that.
